### ISSUE TITLE
Explicitly undefined input causes an error

### ISSUE THREAD

**Issue by lacolaco** [azu/tweet-truncator#3]
When inputting content value is `undefined`, TweetTruncator throws a runtime error.

https://github.com/azu/tweet-truncator/blob/master/src/tweet-truncator.ts#L72

```
TypeError: Cannot read properties of undefined (reading 'length')
```

In my situation below, `desc`  is typed as string or undefined. so `contents["desc"]` is `undefined`. On TypeScript definition, it is valid because `foo?: string` and `foo: string | undefined` are not distinguished commonly.

https://github.com/azu/tweet-truncator/blob/master/src/index.ts#L22

```
  // item.desc is string | undefined
  truncate(
    { desc: item.desc, title: item.title, url: item.url },
    {
      defaultPrefix: '🔖',
      template: '%desc% "%title%" %url%',
      truncatedOrder: ['title', 'desc'],
    },
  );
```

https://github.com/azu/tweet-truncator/blob/master/src/index.ts#L27-L34

```ts
    const fixedContents = {
        desc: "",
        quote: "",
        title: "",
        url: "",
        tags: [],
        ...contents
    };
```

## Suggestion

- override with empty string if inputted value is nullish.

for example:
```ts
    const { desc, quote, title, url, tags, ...unknownContents} = contents;

    const fixedContents = {
        desc: desc ?? "",
        quote: quote ?? "",
        title: title ?? "",
        url: url ?? "",
        tags: tags ?? [],
        ...unknownContents
    };
```

**Comment by azu** [comment]
Thanks!

Fixed in https://github.com/azu/tweet-truncator/releases/tag/v3.0.2
